#!/usr/bin/env python3
"""Build 40 independent, copyable Codex session briefs and an offline dashboard."""
from pathlib import Path
import json,html,zipfile
R=Path(__file__).parent;PROMPTS=R/'prompts';PROMPTS.mkdir(exist_ok=True)
# id,phase,title,repo,assignment,artifact,gate,depends
TASKS=[
(1,'Cash evidence','Reconcile real revenue','founder-os','Read the canonical Sales OS pipeline and actual payment references available to this chat. Separate offerValue, outreach, replies, quotes, captured payments and refunds. Summarize actual paid revenue by Pacific day without copying private records into public files.','A dated, source-linked paid-sales reconciliation and missing-evidence list.','Every claimed dollar traces to a non-test payment event.','none'),
(2,'Cash evidence','Audit current warm leads','founder-os / san-jose-prospecting-pwa','Find genuine warm inquiries from preserved history. Verify consent, recent contact, replies and next action. Do not contact anyone from this session.','A prioritized private warm-lead follow-up queue with exact evidence and opt-outs.','No historical prospect is mislabeled a current buyer.','01'),
(3,'Cash evidence','Choose one San Jose buyer niche','san-jose-prospecting-pwa','Compare mobile grooming, home cleaning and fitness instruction using current verifiable local evidence and fit to existing graphics. Pick one first niche.','One niche brief with ten candidate businesses and dated source links.','No dead, duplicate or invented business is treated as verified.','02'),
(4,'Cash evidence','Verify ten local prospects','san-jose-prospecting-pwa','For the selected niche, verify website/social activity, real offer, service area, contact route and rights to refer to public assets. Respect the PWA pipeline; do not advance statuses.','Ten evidence cards with verified-at timestamps and uncertainty.','Each contact route and business identity can be read back.','03'),
(5,'Offer','Build one private pilot sample','launch-batches / video-playbook','Use only owned or permission-cleared sample media to create one original 30–60 second video and one static graphic for the selected niche. Label sample material.','An MP4, graphic, rights log and preview brief.','Watch the render on phone-sized preview; decode video and read rights notes.','03'),
(6,'Offer','Price the $350 pilot','video-playbook/business','Model the proposed $350 content pilot with delivery hours, revisions, fees, direct costs, refund risk and capacity; compare at least two simpler scopes.','One-page price and scope decision with conservative/base/upside 30-day profit assumptions.','No price is presented as a verified market price.','05'),
(7,'Offer','Make checkout and delivery ready','launch-batches','Inspect the actual connected storefront and seller settings. Prepare exact product, price, scope, refund terms and delivery files. Use test mode for checkout and fulfillment; do not record test purchases as sales.','A reviewable listing and test-mode receipt/delivery result.','Test purchase, delivery and refund path verified by read-back.','06'),
(8,'Offer','Draft individualized buyer approaches','san-jose-prospecting-pwa','Draft ten concise approaches based on verified public facts and the real sample. Do not send messages from this session. Include opt-out handling and clear scope.','Ten drafts each tied to one verified prospect and a reason to care.','Every claim is supportable; no mass generic copy.','04,05,06'),
(9,'Offer','Triage real replies','founder-os / san-jose-prospecting-pwa','Read connected genuine replies, distinguish interested, price, proof, no, opt-out and paid. Draft the next response for each; do not send without explicit action authorization.','A private reply ledger and response drafts.','Reply state does not masquerade as sale or payment.','08'),
(10,'Offer','Fulfill first paid pilot','video-playbook/business','If a genuine paid order exists, produce exactly the agreed deliverables with the provided media, one revision round and delivery evidence. If none exists, finish a dry-run sample and mark it not sold.','Delivery ZIP, QA record and client-ready note, or honest dry-run status.','Delivered files match scope; payment status has actual evidence.','07,09'),
(11,'Products','QA One-Page Offer Kit','launch-batches/2026-10-04/one-page-offer-kit','Inspect PDF, CSV, calculator formulas, copy and license for usability and errors. Fix reversible problems in this product only.','Revised product ZIP and QA note.','PDF renders cleanly; sample math matches formulas.','none'),
(12,'Products','QA Follow-Up Control Kit','launch-batches/2026-10-04/follow-up-control-kit','Check stage definitions, response templates, opt-out handling and CSV import usability. Fix only this kit.','Revised delivery ZIP and buyer instructions.','No sent/replied/quoted/paid stage confusion remains.','none'),
(13,'Products','QA Seven-Day Value Sprint Kit','launch-batches/2026-10-04/seven-day-value-sprint-kit','Check worksheet, daily log, small-sample caveat and worked example. Make the kit easier to complete in one week.','Revised delivery ZIP and QA note.','A sample user can complete one full loop without missing fields.','none'),
(14,'Products','Bundle sales page','launch-batches/2026-10-04','Write a truthful $199 proposed bundle page with exact deliverables, limits, preview, FAQ and post-payment path. Connect checkout only if the actual account works.','Responsive landing page and source copy.','No fake testimonials, income claims or dummy live purchase links.','11,12,13'),
(15,'Products','Five-buyer objection interview','launch-batches','Prepare a five-person buyer interview script and tracking sheet for real conversations. If connected prior responses exist, summarize them; otherwise mark research pending.','Interview guide, hypothesis list and evidence sheet.','No imagined answer is reported as a customer quote.','14'),
(16,'Media','Snarky pilot final script','snarkyhowtos','Read AGENTS, state and handoff. Choose an existing episode topic and revise it into one visually demonstrable 30-second, 90-second and complete full script. Preserve Snarky voice.','Script, shot list, claims table and metadata.','Humor targets broken process, not learner; demonstrated steps work.','none'),
(17,'Media','Oops companion adaptation','snarkyhowtos / video-playbook','Adapt the approved Snarky learning goal for child-oriented Oops Academy with different examples and safe materials. Keep it a separate channel package.','Child-readable script, parent description, shot list and audience designation notes.','Third-grade reading check and no private-child-data prompt.','16'),
(18,'Media','Recover third video project','ai-bridge / connected Drive Ledger','Identify the actual recently worked third video project from the connected Ledger, excluding Sparky per the user correction. If Drive remains unavailable, reconcile local copies and keep identity unresolved.','Evidence-linked project identity or explicit unresolved status.','Do not infer the name from adjacency alone.','none'),
(19,'Media','Render Snarky video','snarkyhowtos','Use rights-cleared real demonstration footage and the approved script to render portrait and landscape versions, captions and cover.','Reviewable MP4s, SRT and thumbnails.','Full video decodes, captions sync and phone preview is legible.','16'),
(20,'Media','Render Oops video','snarkyhowtos / video-playbook','Film or animate the safe child-adapted steps without showing real children or personal records. Render portrait and landscape versions.','Reviewable MP4s, captions and parent-facing cover.','Safety and audience-setting review completed; all shown steps work.','17'),
(21,'Media','Platform maximums and sizes','video-playbook','Check current official YouTube, TikTok and Facebook help plus the actual account uploader for duration, size, format and rights rules. Record checked-at dates.','A live-verified export matrix and changes to presets if needed.','Recording and upload limits are not confused; citations resolve.','none'),
(22,'Story','Rehearse gothic pilot','story-engine/2026-10-04','Read Episodes 001 and 002 aloud, time each scene and mark lines actors cannot play naturally. Revise dialogue while preserving canon rules.','Revised manuscripts with measured timing and change notes.','Each local question resolves and scene actions remain coherent.','none'),
(23,'Story','Improve Episode 002 animatic','story-engine/2026-10-04/animatic-002','Inspect every card, synthetic voice, audio transition, caption and final MP4. Refine the animatic as a preview, labeling it clearly as a stand-in.','Improved 1080x1920 preview and QA log.','Video fully decodes; money remains visibly fictional.','22'),
(24,'Story','Record final actor narration','story-engine/2026-10-04','Plan and capture consented actor voice for Episode 002. Replace the local synthetic narrator only if real recorded audio exists.','Clean dialogue WAVs, rights/consent notes and edit map.','Listen for clipping and intelligibility on phone.','22'),
(25,'Story','Create scriptbook PDF','story-engine/2026-10-04','Lay out the two original plays, cast/production notes and content note as a print-conscious digital scriptbook. No copied franchise artwork.','PDF and accessible source file with cover and contents.','Render each page and inspect typography, margins and text extraction.','22'),
(26,'Story','Originality and rights audit','story-engine/2026-10-04','Compare the series bible and both plays with the broad reference slate. Flag any distinctive protected character, prop, phrase, scene order or design that is too similar; revise original work.','Rights and originality review with exact edits.','No unlicensed media or misleading real-income claim in publishing copy.','22'),
(27,'Research','Get sourced Google Trends snapshot','story-engine/2026-10-04','Use only a permitted live source or user export. Compare exact gothic queries in one geography/time/search-type setting. Save raw evidence; do not manufacture a top ten.','Dated 10-row trends.csv or an access-blocked receipt.','Every rank or index traces to a comparable source row.','none'),
(28,'Research','Verify gothic media market','story-engine/2026-10-04','Check publisher/distributor primary sources and dated audience data for the 12 reference works. Correct the offline market report.','Source-linked success/current-market memo with uncertainty.','Every 2026 claim has checked-at source and no unauthorized scraped data.','27'),
(29,'Research','Map topical queries to original episodes','story-engine/2026-10-04','Use sourced trend input only where a query strengthens a character choice. Propose fresh episodes and skip weak or rights-heavy trends.','Ranked episode concepts with editorial scores and evidence.','No copied IP plot and no normalized index sold as demand.','27,28'),
(30,'Publishing','Prepare portable blog system','story-engine/2026-10-04','Turn the two play blog drafts into accessible portable Markdown/HTML for the actual WordPress/Blogger/identified CMS. Use transcript and click-to-load video.','Two reviewed article packages and CMS mapping.','No live link is invented; page is readable without video.','22,25'),
(31,'Publishing','Build zero-cost story website','story-engine/2026-10-04','Make a fast, responsive static story site with both scripts, captions, cover art, clear fictional status and episode navigation. Do not buy hosting.','Local site and deploy instructions for an available free host.','Mobile keyboard and no-video fallback work; no external publish claim.','25,30'),
(32,'Publishing','Measure page performance','story-engine/2026-10-04','Test current local story site on representative desktop/mobile widths and a slow connection profile where tools allow. Reduce media loading and poster bytes.','Performance/accessibility findings and targeted fixes.','Player does not autoplay; transcript remains accessible.','31'),
(33,'Analytics','Privacy-light content metrics','story-engine/2026-10-04','Design a manual or no-cost metrics ledger for episodes: published URL, impressions, views, duration, retention, shares, qualified visits and sales evidence.','CSV schema and operating instructions.','Actual measured values stay separate from targets and examples.','31'),
(34,'Analytics','Consent-based subscriber flow','story-engine/2026-10-04','Evaluate a truly free, no-card newsletter route with consent and unsubscribe, or leave sign-up absent if terms are unverified. Prepare copy but no messages.','Documented flow and privacy decision.','No unconsented mailing or paid tier enabled.','31'),
(35,'Analytics','Analyze actual audience feedback','story-engine/2026-10-04','After a real release, summarize constructive comments and retention by cut, with dates/sample sizes. If unreleased, prepare analysis template only.','Evidence-linked keep/revise/revert recommendation.','No invented audience result.','33'),
(36,'Money','Test prices with real objections','launch-batches / story-engine','Compare proposed $49/$79/$149 kits, $199 bundle and possible original playbook pricing through real buyer objections, not fictional demand.','Pricing experiment and 30-day unit economics.','No price test presented as revenue before payment.','15,35'),
(37,'Money','Prepare ethical sponsor packet','story-engine/2026-10-04','Draft a narrow sponsor proposal for the original series based only on verified audience and rights. If audience is zero, make a pilot partnership memo without reach claims.','One-page packet, deliverables, exclusions and cash-flow model.','No sponsor names, approvals or income are fabricated.','35'),
(38,'Operations','Build daily evidence dashboard','launch-batches / story-engine','Combine genuine payment/refund events, content metrics and next actions by Pacific day in a local read-only dashboard. Keep private identifiers out of public files.','Dashboard or CSV-based report with honest no-data state.','A test sale is excluded and totals reconcile.','01,33'),
(39,'Operations','Reconcile project ledger','ai-bridge / all relevant repos','Compare story/video/offer artifacts with local project ledger and corrections. Preserve Snarky/Oops separation and exclude Sparky as the third project. Prepare an update for connected Command Center if callable.','Project-status ledger with verified versus draft and next owner.','No external record is called updated without read-back.','18,38'),
(40,'Operations','Run live-action closeout','all current artifacts','Audit all 39 session outputs against evidence. Continue authorized unfinished local work, list external blockers and define the single most valuable next action.','Live Action Update with request ledger and exact file links.','Every completion has a read-back or test receipt.','39'),
]
assert len(TASKS)==40 and [x[0] for x in TASKS]==list(range(1,41))
common='''Account constraint: $0 new cash spend, preferably no card. Use installed/free local tools or already available free account capacity. Do not activate a trial, provision a billable cloud resource, buy ads, hire people, or promise guaranteed revenue. Codex/account usage itself may depend on the user's plan; never claim unlimited free usage.\n\nWorking rule: inspect the exact repo AGENTS.md and current state before editing. Preserve existing files and truthful status. Perform reversible work without repeated confirmation. For any connected public post or record update, prepare the exact content/destination, use the platform's required confirmation and read back the result. Do not send external messages unless explicitly instructed. If a connector or source is unavailable, finish local work and state the blocker.\n'''
items=[]
for n,phase,title,repo,assignment,artifact,gate,depends in TASKS:
 slug=f'{n:02d}-{title.lower().replace(" ","-").replace("$","").replace("/", "-")}'
 brief=f'''# Session {n:02d}: {title}\n\nPhase: {phase}. Depends on: {depends}. Work area: `/workspace/{repo}` when present; locate current source if the workspace layout changed.\n\n{common}\nYour job: {assignment}\n\nRequired deliverable: {artifact}\n\nAcceptance check: {gate}\n\nStart now. Read relevant files, do the authorized work, verify the output and save a concise handoff with exact paths, evidence, unfinished work and next action. If a dependency has not happened, complete its independent preparation and mark only the dependent step blocked. Report sales only from real non-test payment evidence.\n'''
 path=PROMPTS/f'{slug}.md';path.write_text(brief)
 items.append({'id':n,'phase':phase,'title':title,'path':f'prompts/{slug}.md','depends':depends,'area':repo,'deliverable':artifact,'gate':gate,'prompt':brief})
(R/'sessions.json').write_text(json.dumps(items,indent=2))
css='''body{font:17px system-ui;max-width:1100px;margin:24px auto;padding:16px;background:#111827;color:#f8fafc;line-height:1.5}h1{color:#caff42}.card{background:#1e293b;border:1px solid #475569;border-radius:14px;padding:18px;margin:12px 0}button{background:#caff42;border:0;padding:9px 14px;border-radius:7px;font-weight:700;cursor:pointer}a{color:#b9ef79}select{margin-left:8px}small{color:#cbd5e1}textarea{width:100%;height:110px}'''
script='''const data=__DATA__;const root=document.querySelector('#sessions');for(const x of data){const e=document.createElement('div');e.className='card';const title=document.createElement('h2');title.textContent=String(x.id).padStart(2,'0')+' · '+x.title;e.append(title);const desc=document.createElement('p');desc.textContent=x.deliverable;e.append(desc);const meta=document.createElement('small');meta.textContent=x.phase+' · Dependencies: '+x.depends+' · Area: '+x.area;e.append(meta);e.append(document.createElement('br'));const link=document.createElement('a');link.href=x.path;link.textContent='Open prompt';e.append(link);e.append(document.createTextNode('  '));const copy=document.createElement('button');copy.textContent='Copy prompt';copy.onclick=async()=>{try{await navigator.clipboard.writeText(x.prompt);copy.textContent='Copied';setTimeout(()=>copy.textContent='Copy prompt',1500)}catch(err){let area=e.querySelector('textarea');if(!area){area=document.createElement('textarea');e.append(area)}area.value=x.prompt;area.focus();area.select();copy.textContent='Select and copy prompt below'}};e.append(copy);const status=document.createElement('select');for(const label of ['Ready','In progress','Done','Blocked']){const o=document.createElement('option');o.textContent=label;status.append(o)}status.value=localStorage.getItem('codex-session-'+x.id)||'Ready';status.onchange=()=>localStorage.setItem('codex-session-'+x.id,status.value);e.append(status);root.append(e)}'''.replace('__DATA__',json.dumps(items))
(R/'index.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>40 Codex session briefs</title><style>'+css+'</style><h1>40 Codex sessions, ready to launch</h1><p>Open a new Codex chat and paste one brief. This dashboard prepares the sessions; it cannot open chats in your account. Run dependencies in order. Status is stored only in this browser. No sales or account automation is claimed.</p><div id="sessions"></div><script>'+script+'</script></html>')
(R/'README.md').write_text('# 40 Codex session briefs\n\n40 distinct, actionable prompts spanning cash evidence, offers, media, story, publishing, analytics and operations. The first ten target the shortest honest path to a paid test. These are **prepared prompts**, not opened chats or finished jobs. No tool here can create 40 user-visible Codex chats. The offline dashboard copies prompts and saves local status; it does not run them or create accounts. Open `index.html`, launch a new chat manually, paste its prompt and attach/reconnect the workspace if needed. Follow dependencies rather than running conflicting repo edits at once.\n\nThe common $0 constraint refers to no new cash spend in the work plan; this environment cannot guarantee that the user\'s Codex subscription or usage is free. No prompt promises profit. Current project-state corrections, including Sparky exclusion and no verified $10,000 sale, are preserved in the relevant briefs.\n')
with zipfile.ZipFile(R/'40-codex-session-briefs.zip','w',zipfile.ZIP_DEFLATED) as z:
 for p in sorted(R.rglob('*')):
  if p.is_file() and p.name!='40-codex-session-briefs.zip':z.write(p,p.relative_to(R))
print(f'Built {len(items)} sessions')
